### ISSUE TITLE
OMLIB compatibility

### ISSUE THREAD

**Issue by LemADEC** [OpenModularTurretsTeam/OpenModularPassiveDefense#22]
Recent versions of OMPD and OMLIB are incompatible and will crash at boot.
The closest compatible versions found so far are omlib-1.12.2-3.0.1-162 with ompd-1.12.2-3.0.0-36.
More recent versions up to omlib-1.12.2-3.1.0-208 and ompd-1.12.2-3.1.0-49 all seem to reproduce the issue.

**Comment by Keridos** [comment]
Can you please link a crash report for this?

**Comment by LemADEC** [comment]
It seems related to TheOneProbe API:
```
Caused by: java.lang.ClassNotFoundException: omtteam.ompd.blocks.BlockCamoTrap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.NoClassDefFoundError: omtteam/omlib/compatibility/theoneprobe/TOPInfoModifier
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more
Caused by: java.lang.ClassNotFoundException: omtteam.omlib.compatibility.theoneprobe.TOPInfoModifier
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 50 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 52 more
```
https://gist.github.com/LemADEC/a21a42ada78e107aa8d4f080d7d0897a

**Comment by SamboyCoding** [comment]
Can confirm I'm encountering this too https://paste.dimdev.org/duqaxaluhu.mccrash

**Comment by LemADEC** [comment]
Any update on this?

**Comment by Keridos** [comment]
Not yet, I have been very busy IRL, updates on this might take a few more weeks, sorry

**Comment by Keridos** [comment]
Fixed
